### PR TITLE
Highlight lbin from zdharma-continuum/zinit-annex-binary-symlink

### PR DESCRIPTION
**Pull request by anupamsr**

### CODE REVIEW

**Comment by anupamsr** [comment]
Any update? @alichtman

**Comment by alichtman** [comment]
Can you post a screenshot of you testing this?

**Comment by anupamsr** [comment]
After-Before
image

**Comment by anupamsr** [comment]
After-Before
image

**Comment by alichtman** [comment]
Thanks for the contribution!

**Pull request merged**
